oceanbase/obkv-table-client-rs

docs/simple_demo/simple_operation/demo.md
docs/test_tables.sql
src/client/mod.rs
src/client/table.rs
src/client/table_client.rs
tests/test_table_client_base.rs
tests/test_table_client_key.rs
tests/test_table_client_range.rs

- New features, support increment and append
- enhance OBKV client
N.A.
No.
N.A.

[Feat] support append and increment

---

Cargo.lock
Cargo.toml
src/client/ocp.rs

Closes #12 
edit Cargo.toml to make native-tls optional
native-tls is a heavy dep, which depend on openssl on local system, which may cause issue when build host and target host have different openssl version.
none
none
```
➜  obkv-table-client-rs git:(issue12) cargo tree -e features -i reqwest --no-default-features --features rustls-tls
reqwest v0.11.14
├── reqwest feature "__rustls"
│   └── reqwest feature "rustls-tls-webpki-roots"
│       └── reqwest feature "rustls-tls"
│           └── obkv-table-client-rs feature "rustls-tls" (command-line)
├── reqwest feature "__tls"
│   └── reqwest feature "__rustls" (*)
├── reqwest feature "blocking"
│   └── obkv-table-client-rs v0.1.0 (/Users/kous/myProjects/rustproject/obkv-table-client-rs)
│       ├── obkv-table-client-rs feature "reqwest"
│ …
```

edit: make native-tls optional

---

src/location/ob_part_desc.rs
src/serde_obkv/value/mod.rs
tests/test_table_client_base.rs
tests/test_table_client_key.rs

- Fix: support query range in the key partition table, fix #25 
Help users to get data from the key partition table by range query
N.A.
- Notice that the rust client may have different behavior compared to the java client and ODP. Rust will send the query to all the partitions instead of returning an error.
Pass all tests in observer 3.x

[Fix] support range query in key partition

---

docs/test_tables.sql
src/client/table_client.rs
src/location/mod.rs
src/location/ob_part_constants.rs
src/location/ob_part_desc.rs
src/location/util.rs
tests/test_cse_table.rs
tests/test_table_client_key.rs

- Support sub-partition and multi-column in the key partition table, fix #30 and #31.
- Support more functions in the key partition table
N.A.
No
Pass all the tests in observer 3.x

[Feat] support sub-partition and multi-column in key partition

---

src/serde_obkv/value/mod.rs

fix: [[Bug]: incorrect use of decode_vi32 when decoding ObjType::UInt64. ](https://github.com/oceanbase/obkv-table-client-rs/issues/45)
fix: [[Bug]: incorrect use of decode_vi32 when decoding ObjType::UInt64. ](https://github.com/oceanbase/obkv-table-client-rs/issues/45)
No
No
ob server: 3.2.4.3

Fix: changed decode_vi32 to decode_vi64 in ObjType::UInt64 decoding

---

src/serde_obkv/value/mod.rs

- Fix #26 , impl method for user to get data from ``Value``.
- Fix #51 , correct default scale of number.
- Implement method in ``Value`` for users to get double and float.
- Pass all tests.
N.A.

[Fix] obkv serde

---

src/client/table_client.rs
tests/test_table_client_aggregation.rs

Fix: add comment about aggregation tests, change the test names
Fix: add comment about aggregation tests, change the test names
N/A
N/A
N/A
N/A

[Fix] add comment about aggregation tests, change the test names

---

src/client/table_client.rs

Enhancement: #61 
Enhancement: #61

[Enhancement] agg local index support

---

docs/simple_demo/simple_operation/aggregationDemo.md
docs/test_tables.sql
src/client/table_client.rs
tests/test_table_client_aggregation.rs

Add test for ``index_name()`` in aggregation. Also modify demo.
Add test for ``index_name()`` in aggregation.
Pass all tests.
N.A.
N.A.

[Test] add test for index in aggregation

---

src/serde_obkv/value/mod.rs

Fix #66 
Modify VALUE_MAX & VALUE_MIN
All tests.
N.A.
N.A.

[Fix] VALUE MAX & MIN

---

src/serde_obkv/value/mod.rs

Reverts oceanbase/obkv-table-client-rs#67

Revert "[Fix] VALUE MAX & MIN"

---

src/rpc/protocol/codes.rs

Close #71 
- Add error code OB_TRANS_STMT_NEED_RETRY
- Impl retry for OB_TRANS_STMT_NEED_RETRY
Pass all tests except for agg in 3.x
N.A.
N.A.
N.A.

[Fix] concurrent retry

---

Cargo.lock
Cargo.toml

Cherry pick 2391170393fb6b6a7cee58deff0f419fb9da7d27

replace openssl with rustls (#74)

---

src/rpc/mod.rs

This is a cherry-pick of #56 from the branch main to the branch 0.1, and some conflicts has been resolved too.
Refer to the description of #56.

[Fix] uniqueId & traceId (#56)

---

Cargo.lock
Cargo.toml
src/client/query.rs
src/client/table_client.rs
src/error.rs
src/location/mod.rs
src/location/ob_part_desc.rs
src/location/part_func_type.rs
src/location/util.rs
src/rpc/mod.rs
src/rpc/protocol/codes.rs
src/rpc/protocol/mod.rs
src/rpc/protocol/payloads.rs
src/rpc/protocol/query.rs
src/serde_obkv/value/from.rs
src/util/obversion.rs
tests/test_cse_table.rs
tests/test_table_client_aggregation.rs
tests/test_table_client_base.rs
tests/test_table_client_hash.rs
tests/test_table_client_key.rs
tests/utils/common.rs

- Support 4.x observer
- Support 4.x observer

[Feat] support 4.x observer

---

docs/test_tables.sql
rustfmt.toml
src/serde_obkv/value/from.rs
src/serde_obkv/value/mod.rs
tests/test_table_client.rs
tests/test_table_client_base.rs
tests/utils/common.rs

- Support [datetime and timestamp](https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000000222531) in OceanBase
- NaiveDateTime -> datetime(6) (ISO 8601 combined date and time without timezone)
- DateTime<Utc> -> timestamp (the number of non-leap seconds since January 1, 1970 0:00:00 UTC (aka “UNIX timestamp”))

[Feat] datetime & timestamp

---

Cargo.lock
ycsb-rs/Cargo.toml
ycsb-rs/src/main.rs
ycsb-rs/src/properties.rs
ycsb-rs/workloads/workload_obkv.toml

- Show details when in progress of YCSB
- Show details when in progress of YCSB

[Feat] YCSB stat

---

docs/test_tables.sql
src/serde_obkv/value/mod.rs

- Fix time scale
- Fix time scale

[Fix] time scale

---

src/rpc/protocol/lsop.rs
src/rpc/protocol/payloads.rs
src/rpc/protocol/query_and_mutate.rs

- rename set_is_check_not_exists
- rename set_is_check_not_exists

[Chore] rename func

---

src/client/ocp.rs
src/client/table_client.rs
src/util/mod.rs

- Fix GC problem of table client
- Fix GC problem of table client

[Fix] table client GC
